storage:
  folder: ${user.home}/.duplicate-repository

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:h2:./duplicate

server:
  tomcat:
    max-http-form-post-size: 10MB

hibernate:
  dialect: org.hibernate.dialect.H2Dialect

properties:
  count-on-page: "30"


