CREATE TABLE IF NOT EXISTS UPLOADS
(
    ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL
);

ALTER TABLE UPLOADS ADD COLUMN IF NOT EXISTS USERNAME VARCHAR(50) NOT NULL;

CREATE TABLE IF NOT EXISTS DUPLICATES
(
    ID VARCHAR(50) PRIMARY KEY,
    UPLOAD_ID VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PARTS
(
    ID VARCHAR(50) PRIMARY KEY,
    DUPLICATE_ID VARCHAR(50) NOT NULL,
    NAME VARCHAR(1000) NOT NULL,
    FILE VARCHAR(1000) NOT NULL,
    IS_SELECTED BOOLEAN NOT NULL,
    IS_DELETED BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS PARTS_DELETED_INFO
(
    PART_ID VARCHAR(50) PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    DELETED_DATE TIMESTAMP NOT NULL
);

